Repository FRONTENDSCHOOL10/coding13-euid, pull requests merged in 2024-07, with the labels that each got.

#65 이미지파일 정리 및 favicon 추가
  public/icon/alarm-bell.svg
  public/icon/board.svg
  public/icon/category-plus.svg
  public/icon/chat.svg
  public/icon/check.svg
  public/icon/checked.svg
  public/icon/close.svg
  public/icon/delete.svg
  public/icon/direction-down.svg
  public/icon/direction-left.svg
  public/icon/direction-right.svg
  public/icon/full-board.svg
  public/icon/full-chat.svg
  public/icon/full-home.svg
  public/icon/full-map.svg
  public/icon/full-my.svg
  public/icon/hamburger.svg
  public/icon/heart.svg
  public/icon/home.svg
  public/icon/information.svg
  public/icon/map.svg
  public/icon/more.svg
  public/icon/my.svg
  public/icon/pagination-bar.svg
  public/icon/pencil.svg
  public/icon/people.svg
  public/icon/plus.svg
  public/icon/polygon.svg
  public/icon/profile.svg
  public/icon/qna.svg
  public/icon/qr.svg
  public/icon/right.svg
  public/icon/search.svg
  public/icon/send.svg
  public/icon/share.svg
  public/icon/speech.svg
  public/icon/time.svg
  public/logo.webp
  src/api/pocketbase.js
  src/assets/logo.png
  src/assets/position.png
  src/components/header/header.js
  src/components/navigation/navigation.js
  src/pages/category/index.html
  src/pages/chat-content/index.html
  src/pages/chat/index.html
  src/pages/edit-profile/index.html
  src/pages/exchange-detail/index.html
  src/pages/exchange/components.html
  src/pages/exchange/index.html
  src/pages/login/index.html
  src/pages/profile-detail/index.html
  src/pages/profile/index.html
  src/pages/search-result/index.html
  src/pages/search/components.html
  src/pages/search/index.html
  src/pages/signup/index.html
  src/pages/start/index.html
Labels: 📂 파일 수정

#85 Feature/exchange detail/joowon
  public/icon/heart-solid.svg
  src/pages/chat-content/chat-content.js
  src/pages/exchange-detail/exchange-detail.js
  src/pages/exchange-detail/index.html
  src/utils/debounce.js
Labels: 👍 새로운 기능

#90 chat-content 페이지
  src/components/modal/modal.js
  src/pages/chat-content/chat-content.js
  src/pages/chat-content/index.html
Labels: 👍 새로운 기능

#92 Feature/login/jisoo
  src/pages/login/index.html
  src/pages/login/login.js
  src/pages/login/login2.html
  src/pages/login/login2.js
  src/pages/signup/index.html
  src/pages/signup/signup.js
  src/pages/signup/signup2.html
  src/pages/signup/signup2.js
Labels: 🛠️ 리팩토링

#88 Feature/search/gahyun
  src/pages/search/components.html
  src/pages/search/index.html
  src/pages/search/search.js
Labels: 👍 새로운 기능

#93 module refactoring for profile pages, webp avatars
  package-lock.json
  package.json
  public/assets/avatar-placeholder.png
  public/assets/reviews-avatar-placeholder.png
  src/pages/edit-profile/edit-profile.js
  src/pages/edit-profile/index.html
  src/pages/profile-detail/index.html
  src/pages/profile-detail/profile-detail.js
  src/pages/profile/index.html
  src/pages/profile/profile.js
  src/utils/calculateAspectRatioSize.js
  src/utils/convertImageToWebP.js
  src/utils/getImageSize.js
Labels: 👍 새로운 기능, 🛠️ 리팩토링

#99 Feature/write post/joowon
  public/icon/camera.svg
  public/icon/location.svg
  src/components/header/header.js
  src/components/modal/modal.js
  src/pages/chat-content/chat-content.js
  src/pages/chat-content/index.html
  src/pages/write-post/index.html
  src/pages/write-post/write-post.js
  vite.config.js
Labels: 👍 새로운 기능

#95 Feature/search result/gahyun
  src/pages/search-result/index.html
  src/pages/search-result/search-result.js
Labels: 👍 새로운 기능

#101 Feature/category/jisoo
  src/pages/category/category.js
  src/pages/category/index.html
  src/pages/signup/signup2.js
  src/service/UserService.js
Labels: 👍 새로운 기능

#111 [start, login, signup, chat, category] 접근성 체크 및 module import 수정
  src/pages/category/index.html
  src/pages/chat/chat.js
  src/pages/chat/index.html
  src/pages/login/index.html
  src/pages/login/login2.html
  src/pages/login/login2.js
  src/pages/signup/index.html
  src/pages/signup/signup2.html
  src/pages/signup/signup2.js
  src/pages/start/index.html
Labels: 🛠️ 리팩토링

#112 [profile, edit-profile, profile-detail] 접근성 체크 및 module import 수정
  src/pages/edit-profile/edit-profile.js
  src/pages/edit-profile/index.html
  src/pages/profile-detail/index.html
  src/pages/profile-detail/profile-detail.js
  src/pages/profile/index.html
  src/pages/profile/profile.js
Labels: 🛠️ 리팩토링

#115 rename: 이미지파일 webp로 변경 및 경로 수정
  public/assets/avatar-placeholder.png
  public/assets/reviews-avatar-placeholder.png
  public/avatar-placeholder.webp
  public/profile-placeholder.webp
  public/reviews-avatar-placeholder.webp
  src/assets/exchangeItem.png
  src/assets/profileIcon.png
  src/pages/chat-content/index.html
  src/pages/chat/chat.js
  src/pages/edit-profile/edit-profile.js
  src/pages/exchange-detail/index.html
  src/pages/profile-detail/profile-detail.js
  src/pages/profile/profile.js
Labels: 📂 파일 수정

#119 Feature/lighthouse feedback/joowon
  src/components/header/header.js
  src/main.js
  src/pages/board/index.html
  src/pages/chat-content/chat-content.js
  src/pages/chat-content/index.html
  src/pages/chat/chat.js
  src/pages/chat/index.html
  src/pages/exchange-detail/exchange-detail.js
  src/pages/exchange/exchange.js
  src/pages/exchange/index.html
  src/pages/login/index.html
  src/pages/login/login2.html
  src/pages/profile-detail/index.html
  src/pages/search-result/index.html
  src/pages/signup/index.html
  src/pages/signup/signup2.html
  src/pages/write-post/write-post.js
Labels: 🛠️ 리팩토링

#120 main 페이지 리팩토링,search result 페이지 중첩필터 구현
  src/main.js
  src/pages/search-result/search-result.js
  src/pages/search/search.js
  src/styles/global.css
Labels: 👍 새로운 기능, 🛠️ 리팩토링
